# Generated by Django 3.2.6 on 2021-12-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_cv_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photo'),
        ),
    ]
