# Generated by Django 3.2.6 on 2021-12-23 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_alter_cv_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='biograpy',
            field=models.TextField(max_length=400),
        ),
    ]
