# Generated by Django 3.2.6 on 2022-01-16 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cv', '0005_profil'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profil',
            options={'permissions': (('commenter_article', 'commenter article'), ('maeque_lu', 'Marquer comme lu'))},
        ),
        migrations.AddField(
            model_name='profil',
            name='site_web',
            field=models.URLField(null=True),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('contenu', models.TextField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
