# Generated by Django 3.2.6 on 2022-01-19 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0008_auto_20220116_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='avatar',
            field=models.ImageField(blank=True, default='WhatsApp_Image_2020-12-29_at_10.53.46.jpeg', upload_to='img'),
        ),
    ]
